name: blender-fake-addon

on: 
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        blender-version: ["2.80"] # ["2.78c", "2.79b", "2.80", "2.81a", "2.82", "2.83"]
        os: [ubuntu-latest] #, windows-latest]
        #blender-version: ["2.80"]
        #os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        # Grab blender-fake-addon
        wget https://github.com/douglaskastle/blender-fake-addon/archive/master.zip
        unzip master.zip
        cd blender-fake-addon-master/
        mv scripts/ tests/ fake_addon/ blender_requirements.txt ..
        cd ..
    - name: Download Blender ${{ matrix.blender-version }} and testing it with pytest
      run: |
        pip install -r scripts/requirements.txt 
        pip install -r blender_requirements.txt
        yolk -l
        python scripts/get_blender.py ${{ matrix.blender-version }}
        python scripts/run_blender.py ${{ matrix.blender-version }}
