name: gmic-blender-testing

on: 
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        blender-version: ["2.80"] # ["2.78c", "2.79b", "2.80", "2.81a", "2.82", "2.83"]
        os: [ubuntu-latest] #, windows-latest]
        #blender-version: ["2.80"]
        #os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Download Blender ${{ matrix.blender-version }} and test it with pytest
      run: |
        bash make_addon_zip.bash
        pip install -r blender_addon_tester_requirements.txt
        python test_gmic_blender_addon.py
